name: Publish a release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
      release_name:
        required: true
        type: string
jobs:
  gh_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ github.event.inputs.tag_name }}"
          name: "${{ github.event.inputs.release_name }}"
