name: Publish a release

on:
  workflow_dispatch:
    inputs: {}

env:
  PR_BRANCH: release-ci-${{ github.sha }}

jobs:

  gh_release:
    runs-on: ubuntu-latest
    outputs:
      release_number: ${{ steps.determine_number.outputs.release_number }}
    env:
      GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Determine release number
        id: determine_number
        run: |
          echo release_number=$(( 1 + $(gh release list --json tagName | 
            jq --raw-output '.[] | .tagName' |
            cut -d '-' -f 2 |
            sort -n -r |
            head -n 1) )) >> "$GITHUB_OUTPUT"

      - name: Create branch
        run: |
          git switch -c ${{ env.PR_BRANCH }}

      - name: Update changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --tag "release-${{ steps.determine_number.outputs.release_number }}"
        env:
          OUTPUT: CHANGELOG.md

      - name: Generate release notes
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --tag "release-${{ steps.determine_number.outputs.release_number }}" --unreleased --strip all
        env:
          OUTPUT: release_notes.md

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Jan Buchar
          author_email: ci@bucharjan.cz
          message: "chore(release): Release ${{ steps.determine_number.outputs.release_number }}} [skip ci]"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "release-${{ steps.determine_number.outputs.release_number }}"
          name: "Release ${{ steps.determine_number.outputs.release_number }}"
          target_commitish: ${{ steps.commit.outputs.commit_long_sha || github.sha }}
          body_path: release_notes.md

  prepare_pkgbuild:
    runs-on: ubuntu-latest
    needs: gh_release
    env:
      TARBALL_URL: https://github.com/janbuchar/rorqual/archive/refs/tags/release-${{ needs.gh_release.outputs.release_number }}.tar.gz
      RELEASE_NUMBER: ${{ needs.gh_release.outputs.release_number }}
      GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Use cache
        uses: actions/cache@v4
        with:
          path: out/
          key: ${{ github.run_id }}
      - name: Prepare output dir
        run: mkdir -p out
      - name: Create requirements.txt
        run: |
          uv export --format requirements-txt --no-hashes --no-dev -o out/requirements.txt
          cat out/requirements.txt
      - name: Copy launcher
        run: cp aur/rorqual out/rorqual
      - name: Create PKGBUILD
        run: |
          cat aur/PKGBUILD.template | 
            TARBALL_HASH=$(gh api $TARBALL_URL | sha256sum | cut -f 1 -d " ") \
            REQUIREMENTS_HASH=$(sha256sum out/requirements.txt | cut -f 1 -d " ") \
            LAUNCHER_HASH=$(sha256sum out/rorqual | cut -f 1 -d " ") \
            envsubst '${TARBALL_URL} ${RELEASE_NUMBER} ${TARBALL_HASH} ${REQUIREMENTS_HASH} ${LAUNCHER_HASH}' > out/PKGBUILD
          cat out/PKGBUILD

  aur_push:
    runs-on: ubuntu-latest
    needs: prepare_pkgbuild
    steps:
      - name: Use cache
        uses: actions/cache@v4
        with:
          path: out/
          key: ${{ github.run_id }}
      - name: Prepare output dir
        run: mkdir -p out
      - name: Setup AUR SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AUR_PRIVATE_KEY }}
      - name: Checkout AUR package
        run: |
          mkdir -p .ssh
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          git init
          git remote add origin ssh://aur@aur.archlinux.org/rorqual-venv.git
          git pull origin master
      - name: Apply changes
        run: |
          mv out/* ./
          rm -rf out
      - name: Prepare .SRCINFO
        uses: heyhusen/archlinux-package-action@v2.2.1
        with:
          flags: ''
          namcap: false
          srcinfo: true
      - name: Push to AUR
        run: |
          git config --global user.email "ci@bucharjan.cz"
          git config --global user.name "Jan Buchar"
          git add .
          git commit -m "Release ${{ needs.gh_release.outputs.release_number }}"
          git push origin master
